### ISSUE TITLE
Unable to run the script in Ubuntu/Linux

### ISSUE THREAD

**Issue by sg0wtham** [sammmlow/ORBITM#1]
When I cloned the repo in Linux/Ubuntu and trying to execute the `orbitm.py`, I end up with the `ImportError`
`ImportError: cannot import name 'COMError' from '_ctypes'`. I am using Anaconda as the Python environment.

Is the script only made for Windows? If so, is there a way to get it working in Ubuntu/Linux?

**Comment by sammmlow** [comment]
Have you tried running it in Windows?

One possibility is that you might be trying to run it on either of the STK modes when you don't have a licensed copy of STK Integration or STK Astrogator. You need those two licenses on top of either STK 10 or STK 11 installed. In the native orbit maintenance simulation (Sam's mode), ORBITM should still work, as the COM library should not even be importing in the native simulation mode. Let me know if there is still an issue.

**Comment by sg0wtham** [comment]
Thank you for a quick reply. I did not try in Windows. 
I am not able to get the GUI itself (to select the mode). I get the `ImportError` when I try to do `python orbitm.py`.

**Comment by sammmlow** [comment]
You're probably missing COM because COM is a Windows library (since STK is a windows software).

In that case, you can goto the file ORBITM/codes/orbitm_tkinter_ui.py, and comment or delete this line 33 in the code

`from codes.orbitm_run_stk import orbm_run_stk`

If that still doesn't work, try importing any of the following libraries in your Python terminal and see which are the libraries you don't have.

```
import numpy
import matplotlib
import tkinter
import PIL
import os
import math
import datetime
```

**Comment by sg0wtham** [comment]
Commenting the line 
`from codes.orbitm_run_stk import orbm_run_stk`

and changing line 91 from
`orbitm_logo = orbitm_logo + '\gui\orbm_logo.png'`
to
`orbitm_logo = os.path.join(orbitm_logo, 'gui', 'orbm_logo.png')`

did the job. Now the GUI seems to boot up. Thank you for the guidance.

**Comment by sammmlow** [comment]
Thanks for pointing out the bug, Gowtham! I’ll try to see if I can organise the code in such a way where it’s Linux friendlier.
