### ISSUE TITLE
Graphing not working

### ISSUE THREAD

**Issue by tomeetom22** [sammmlow/ORBITM#2]
Hi there, thanks for the tool.

I can't seem to get the graphs generating. I'm using sams if that matters. I've looked at the source code just added a blanket plt.show() at the end of the run_offline code, but the graphs are formatted really weirdly... do I need to format this myself or is something off? Let me know if there's a fix.

Thanks for the good work!

**Comment by sammmlow** [comment]
Hey Tom! Thanks for the feedback, I've had issues with plotting for the STK mode but not Sam's mode for now. I just tested it out and it works fine on mine. I'm using a Windows 10, Python 3.8 in a Conda environment and Numpy 1.18. I doubt it's a matplotlib issue.

Hmm could you post an image of what you see on the plots? Post any raised exceptions or error messages you see too.

**Comment by tomeetom22** [comment]
Sure thing. I'm using the most recent version of both python (3.9) and numpy (1.20.3) but not in a virtual environment. 
![orbitmfig1](https://user-images.githubusercontent.com/53416645/120377821-a10cb600-c2eb-11eb-8a94-9af4f4884aaf.png)
![orbitmfig2](https://user-images.githubusercontent.com/53416645/120377822-a10cb600-c2eb-11eb-8bb8-c4bc42ba7199.png)
![orbitmfig3](https://user-images.githubusercontent.com/53416645/120378686-ba623200-c2ec-11eb-8e0c-c61c31133b2f.png)

**Comment by tomeetom22** [comment]
Also Looks like it does add bars to fig 3 when only one thrustor is setup

**Comment by sammmlow** [comment]
It's likely that the thruster_shortlist.txt file is formatted in a weird way; might just be an input formatting issue. Could you paste what you see in the thruster shortlist text file?

**Comment by tomeetom22** [comment]
[thruster_shortlist - Copy.txt](https://github.com/sammmlow/ORBITM/files/6587295/thruster_shortlist.-.Copy.txt)

**Comment by sammmlow** [comment]
I've tested it out on a fresh re-install of Anaconda (so all my packages were reinstalled to factory default Anaconda Individual Edition). Numpy version is 1.20.1, matplotlib version is 3.3.4. Then I re-ran ORBITM using Sam's simulator and everything works perfectly fine (and everything worked perfectly fine before the rieinstall just to be clear). In both cases before and after, I included the extra "plt.show()" line you had in your comment (I am not sure why it is needed though). It still works though. 
I am using the example `thruster_shortlist.txt` file you have.

![graph_not_working_test01](https://user-images.githubusercontent.com/17903127/120631809-de637600-c49a-11eb-8574-4ead94b0403c.png)

Two possibilities:
1) You might have really outdated version of NumPy or Matplotlib
2) You might have accidentally deleted another line during the bar chart plot.

Try re-cloning the repository again and seeing if you get the same problem on a fresh build.

**Comment by tomeetom22** [comment]
Sweet thanks dude. Should I need Anaconda? Re-installed the repo and it won't show graphs by default and it looks wonky once I add the plt.show()... Both my NumPy and Matplotlib versions are ahead of yours so that could have to do with it too...

**Comment by tomeetom22** [comment]
Ok got it to work but I needed a plt.show right before the return none in the offline python script. Is there some other way this is supposed to be displaying the graphs? I haven't had too much experience with matplotlib, but I don't see any other plt.show() and I was pretty sure you needed that to display the graphs...

**Comment by sammmlow** [comment]
Thanks, I looked into this further, and for vanilla Python users (meaning you're running Python in non-interactive or non PyLab mode), the plots don't show up by default and you are right, you do need `plt.show()`. However, if you're using an IDE like Spyder or Jupyter Notebook, with an active IPython console, you are running Python in a interactive mode and thus you don't need `plt.show()`. In the latter case, plots should pop out either inline or pop out as separate windows showing plots.

Thanks for pointing this out. I will pin this up as an issue to fix for future builds! For now, simply include `plt.show()` before the `return None` and you should be fine.
