### ISSUE TITLE
Summary output does not display time properly?

### ISSUE THREAD

**Issue by ramalash98** [sammmlow/ORBITM#5]
Hey Sam!

Although Orbitm tells you when the satellite would hit the Karman line, the output just says "0" :S

![image](https://user-images.githubusercontent.com/94207362/141601618-8c5618c4-e67e-4fa2-9073-a393e6ccd2a1.png)

**Comment by sammmlow** [comment]
That's strange. Usually it does that if the simulation doesn't hit the Karman line within the 10 year frame, but for 6678km SMA it should. I'll check it out, thanks for pointing it out!

**Comment by sammmlow** [comment]
Done! Fixed, it should work right now, thanks for pointing out the bug!
